// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Core.Persistence.Contexts;

namespace Tests.Database.Migrations
{
    [DbContext(typeof(ChurchContext))]
    internal class ChurchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel (ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");
            modelBuilder.Entity("Core.Persistence.Models.ChurchModel", b =>
            {
                b.Property<string>("Id")
                    .HasColumnType("TEXT");
                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("churches");
            });
#pragma warning restore 612, 618
        }
    }
}
