// <auto-generated />
using System;
using Idigis.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Idigis.Tests.IntegrationTests.Persistence.Helpers.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Idigis.Core.Persistence.Models.ChurchModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("churches");
                });

            modelBuilder.Entity("Idigis.Core.Persistence.Models.MemberModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BaptismDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChurchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("Idigis.Core.Persistence.Models.OfferModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChurchId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChurchId");

                    b.ToTable("offers");
                });

            modelBuilder.Entity("Idigis.Core.Persistence.Models.TitheModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChurchModelId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChurchModelId");

                    b.HasIndex("MemberId");

                    b.ToTable("tithes");
                });

            modelBuilder.Entity("Idigis.Core.Persistence.Models.MemberModel", b =>
                {
                    b.HasOne("Idigis.Core.Persistence.Models.ChurchModel", "Church")
                        .WithMany("Members")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("Idigis.Core.Persistence.Models.OfferModel", b =>
                {
                    b.HasOne("Idigis.Core.Persistence.Models.ChurchModel", "Church")
                        .WithMany("Offers")
                        .HasForeignKey("ChurchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Church");
                });

            modelBuilder.Entity("Idigis.Core.Persistence.Models.TitheModel", b =>
                {
                    b.HasOne("Idigis.Core.Persistence.Models.ChurchModel", "ChurchModel")
                        .WithMany()
                        .HasForeignKey("ChurchModelId");

                    b.HasOne("Idigis.Core.Persistence.Models.MemberModel", "Member")
                        .WithMany("Tithes")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChurchModel");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Idigis.Core.Persistence.Models.ChurchModel", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Offers");
                });

            modelBuilder.Entity("Idigis.Core.Persistence.Models.MemberModel", b =>
                {
                    b.Navigation("Tithes");
                });
#pragma warning restore 612, 618
        }
    }
}
