name: api deploy
on:
  push:
    branches: [main]
    paths:
      - src/Idigis.Api/**
      - src/Idigis.Core/**
      - src/Idigis.Shared/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.200

      - name: Testing
        env:
          ClientUrl: "https://0.0.0.0/"
          ServerUrl: "https://0.0.0.0/"
          JwtSecret: "randomV23U5i4a1OvVDOwbDAT"
        run: chmod +x run && ./run test:coverage
      
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Build API
        run: ./run api:build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_API }} 
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
