name: test
on:
  pull_request:
    branches: [develop, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.200
      - name: Install dependencies
        run: dotnet restore
      - name: Testing
        run: chmod +x run && ServerUrl=https://0.0.0.0 JwtSecret=any_secret ./run test
