name: .NET CI
on:
  pull_request:
    branches: [develop, stable]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.200
      - name: Install dependencies
        run: dotnet restore
      - name: Testing
        env:
          Client: "https://0.0.0.0/"
        run: dotnet test --nologo /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=../coverage/lcov.info /p:ExcludeByFile=\"**/Migrations/*.cs\"
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
