name: test
on:
  pull_request:
    branches: [develop, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.200
      - name: Install dependencies
        run: dotnet restore
      - name: Testing
        env:
          ClientUrl: "https://0.0.0.0/"
          ServerUrl: "https://0.0.0.0/"
          JwtSecret: "example_example_example_example_example_example_example_example"
          JwtExpirationInHours: 2
        run: chmod +x run && ./run test
        env:
          ServerUrl: https://0.0.0.0
          JwtSecret: rV23U5i4a1OvVDOwbDAT 
